### PR TITLE
Improve SCORM disk storage handler

### PR DESCRIPTION
**Pull request by KhaledLela**
- refactor(manager): fix manager duplicated storage code, make it depend on ScormDist helper
   - Control scorm storage and handle unzip and store on different storage local/cloud.
- code format and same UUID but under laravel support helper
- add extra doc on scorm config file including example for explanation
- update README with step 3 of update config cache, and add optional step to describe scorm disk handler with example.
- fix scorm update archive with updateOrCreated, drop old scorm package when already exists.

### CODE REVIEW

**Comment by haithamrdina** [comment]
hello khalid ,
u had an example using this bundle please if u can a doc to use this
package
thank u

Le lun. 7 févr. 2022, 10:49, Khaled Mohamed ***@***.***> a
écrit :

**Comment by KhaledLela** [comment]
FYI: 
- This library for unzip and parse scorm package manifest file and store into database tables.
- NOT for running SCORM  => you will need to handle runtime scripts other ways, Like [scorm-again](https://github.com/jcputney/scorm-again)
- NOT for Creating SCORM package, you can check [Starting-from-SCORM-A-Developers-Guide] to know more about structure (https://github.com/adlnet/Starting-from-SCORM-A-Developers-Guide/blob/master/Instructions.md)


- Check README file for installation instructions.
- to use my fork 
 ```
    "require": {
        "php": ">=7.4",
        "ext-json": "*",
         // ... other dependency 
        "devianl2/laravel-scorm": "dev-main"
    },
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/KhaledLela/laravel-scorm"
        }
    ],
```

- Usage:
```
class ScormController extends BaseController
{
    /** @var ScormManager $scormManager */
    private $scormManager;
    /**
     * ResourceController constructor.
     * @param ScormManager $scormManager
     */
    public function __construct(ScormManager $scormManager)
    {
        $this->scormManager = $scormManager;
    }


    public function store(ScormRequest $request)
    {
        $scorm = $this->scormManager->uploadScormArchive($request->file('file'));
        return $this->respond($scorm);
    }
}
```
- Config

```
// config/scorm.php
<?php

return [

    'table_names' =>  [
        'user_table'   =>  'users',
        'scorm_table'   =>  'scorm',
        'scorm_sco_table'   =>  'scorm_sco',
        'scorm_sco_tracking_table'   =>  'scorm_sco_tracking',
    ],
    /**
     * Scorm directory. You may create a custom path in file system
     * Define Scorm disk under @see config/filesystems.php
     */
    'disk'  =>  's3-scorm',
];
```

```
// config/filesystems
    'disks' => [

        'local' => [
            'driver' => 'local',
            'root'   => storage_path('app'),
        ],

        'public' => [
            'driver'     => 'local',
            'root'       => storage_path('app/public'),
            'visibility' => 'public',
        ],

        's3' => [
            'driver' => 's3',
            'key'    => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
        ],

        's3-scorm' => [
            'driver' => 's3',
            'root'   => env('SCORM_ROOT_DIR'),
            'key'    => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_SCORM_BUCKET'),
        ],
    ],
```


**Hopefully this will help you,**

**Comment by haithamrdina** [comment]
thank u so much it so helpful for any update  i will ask u thank u so much  for my educationnal project i need to create simple lms with scorm integration and tracking students sco if u have any informations u can share it with me thank you sir

**Review by devianl2 — APPROVED** [review]
Thank you for the update.  Do you mind to share what's the function for ScormModel::whereOriginFile() that you use in ScormManager?

**Comment by haithamrdina** [comment]
hi @devianl2/laravel-scorm
***@***.***> ,
there are no examples for saving progress ?
if you can make an example to see how do it
thanks

**Pull request merged**
