### PR TITLE
Handle publish translations for scorm runtime exceptions handler

### PR DESCRIPTION
**Pull request by KhaledLela**
- handle publish scorm runtime exception msg keys as translation under resources/lang/en-US/scorm.php
- update readme with translation part and usage example.

### CODE REVIEW

**Comment by haithamrdina** [comment]
when i use form to upload file 
i had this error
Capture

**Comment by haithamrdina** [comment]
you have to change the database schema for the scorm table, right?

**Comment by haithamrdina** [comment]
sir u can help for tracking user tracking sco

**Comment by haithamrdina** [comment]
Capture

i get this error how to solve it  ?? 
i think in scorm table will change   $table->morphs('resource');  wth $table->nullableMorphs('resource'); 

right ??

**Comment by KhaledLela** [comment]
> Capture
> 
> i get this error how to solve it ?? i think in scorm table will change $table->morphs('resource'); wth $table->nullableMorphs('resource');
> 
> right ??

- Try to fork and update til get it working and PR.
- update composer require like: (change: `YOUR_BRANCH_NAME`, `YOUR_USER_AME`)


   "require": {
       "php": ">=7.4",
       "ext-json": "*",
        // ... other dependency 
       "devianl2/laravel-scorm": "dev-{YOUR_BRANCH_NAME}"
   },
"repositories": [
       {
           "type": "vcs",
           "url": "https://github.com/{YOUR_USER_AME}/laravel-scorm"
       }
   ],

**Comment by haithamrdina** [comment]
u have any about playing scorm and traching user sco.??

**Comment by devianl2** [comment]
Hi @haithamrdina , resource_type and resource_id is for your scorm to make a reference to e-learning module and ID.

For example, you created a course and starting to create module with module title and upload the scorm file. After you'd created the module record, you can call something like $module->scorm()->save($scorm);

**Pull request merged**
